name: CI

on:
  push:
  pull_request:
  schedule:
    - cron:  '0 12 * * fri' # Friday noon
  repository_dispatch:
    types: request-retest

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]
        node: [ latest, 'lts/*' ]

    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - run: npm install
    - run: npm test
